### ISSUE TITLE
Name of frietkot?

### ISSUE THREAD

**Issue by JonasVW** [JonasVW/WebTech2015#1]
Naming it just "frietkot" is a bit... well, stupid. 
Anyone has an idea for a name ? 

The Shining Fries ? 

I dunno, Gerd, what do you think?

**Comment by GVanBuggenhout** [comment]
Fries = American English = Bad

But I can't come up with a decent name right now

**Comment by GVanBuggenhout** [comment]
Armoured WarChipz is the name of the frietkot
